cd Rounded
del *.png
cd windows
del *.png
cd ..
cd social
del *.png
cd ..
cd apple
del touch-icon-iphone.png
del touch-icon-ipad.png
del touch-icon-iphone-retina.png
del touch-icon-ipad-retina.png
cd ..
del Android\ic_launcher-web.png
del Android\drawable-hdpi\ic_launcher.png
del Android\drawable-ldpi\ic_launcher.png
del Android\drawable-mdpi\ic_launcher.png
del Android\drawable-xhdpi\ic_launcher.png
del Android\drawable-xxhdpi\ic_launcher.png
cd ..

cd Square
del *.png
cd windows
del *.png
cd ..
cd social
del *.png
cd ..
cd apple
del touch-icon-iphone.png
del touch-icon-ipad.png
del touch-icon-iphone-retina.png
del touch-icon-ipad-retina.png
cd ..
del Android\ic_launcher-web.png
del Android\drawable-hdpi\ic_launcher.png
del Android\drawable-ldpi\ic_launcher.png
del Android\drawable-mdpi\ic_launcher.png
del Android\drawable-xhdpi\ic_launcher.png
del Android\drawable-xxhdpi\ic_launcher.png
cd ..

del *.ico

del Banners\*.png
del Screenshots\*.png
del Splashscreens\*.png